### ISSUE TITLE
Different zoom level compared to poppler backend

### ISSUE THREAD

**Issue by philacs** [xylosper/okular-backend-mupdf#2]
Hi, I tested this through Arch AUR package, and I found mupdf rendering is smaller than poppler rendering on the same zoom level. Following is a screenshot showing a comparison.

![poppler_vs_mupdf](https://cloud.githubusercontent.com/assets/881147/5422722/6034a188-8247-11e4-87e9-4cf92d4fa932.png)

Left-Up is poppler 100%, Right-Up is mupdf 100%.
Left-Down is poppler 400%, Right-Down is mupdf 400%.

The whole screen resolution is 2560x1080, the pdf is generated using Adobe InDesign CS 3.0.1

**Comment by xylosper** [comment]
Thank you for point it out.
I found that MuPDF always assumes 72dpi which is not true.
I fixed this in a7e66323992cef2b38166128105763f10a963469.
