### ISSUE TITLE
Navigation using Table of Contents not working

### ISSUE THREAD

**Issue by dschoepe** [xylosper/okular-backend-mupdf#3]
Jumping to a section by clicking on an entry in the Contents pane of Okular does not work when using the mupdf backend. This happens with both, version 14.12.3 of Okular (using the Arch Linux package), and the latest git checkout of okular.

This happens consistently with all documents I tried. All of them work fine using the Poppler backend. There is no output on the terminal indicating any error. Here's an example document where this happens: http://schoepe.org/~daniel/example.pdf

**Comment by xylosper** [comment]
Implemented. Thank you.

**Comment by abulak** [comment]
Oh, cool!

I stopped using mupdf-backend but for kile-git preview, so I didn't miss that feature, but it's definitely nice to have!
